### PR TITLE
fix: revert changes for bias & scale

### PR DESCRIPTION
**Pull request by beersandrew**
- fixes were made recently to appease usdchecker with respect to warnings about bias and scale, however these values are intentional for this asset, reverting them to how they were

https://github.com/usd-wg/assets/commit/eefd571edfc456cebf3b213efcca87f51b1a4654#r124902221

### CODE REVIEW

**Comment by beersandrew** [comment]
> Thanks, fast work! I'm in the process of revising this test model's lighting and other characteristics based on the feedback and PR from @pablode #44 feedback
> 
> It will have this fix and the Dome Light orientation fix, as well as the inputs:intensity problem mentioned there. So, please hold off on approving these two PRs, to help me avoid merge headaches. Mine should work a bit better, I hope.
> 
> I would submit my PR today, but am having problems myself with running usdchecker on a new PC. Hopefully I'll have that sorted in a day or so.

sounds good!

**Comment by erich666** [comment]
I've restored the bias and scale values in [this PR](https://github.com/usd-wg/assets/pull/52), along with other issues discussed in https://github.com/usd-wg/assets/pull/44

So, I think this PR can be closed (and not used), as the new PR also fixes them.

**Comment by hybridherbst** [comment]
Related to
- https://github.com/PixarAnimationStudios/OpenUSD/issues/2606

**Comment by jcowles** [comment]
Closing per https://github.com/usd-wg/assets/pull/51#issuecomment-1692161704 
Thanks all!

**Pull request closed without merging**
