### PR TITLE
Add test asset for alpha sorting, depth testing etc. in UsdPreviewSurface

### PR DESCRIPTION
**Pull request by hybridherbst**
[Direct link to the Readme with various screenshots](https://github.com/prefrontalcortex/usd-wg-assets/tree/alpha-sort-test/test_assets/AlphaBlendSortTest)

Kind of a follow-up to the other transparency/blend mode test asset and to the discussions in https://github.com/erich666/McUsd/issues/1 - 
this asset is a simple "baked shadow plane" test but I haven't been able to understand how it should correctly look with UsdPreviewSurface. Before it can be merged that should be clarified.

cc @meshula

### CODE REVIEW

**Comment by meshula** [comment]
Good idea for a test. I was wondering if the plan is for all the images to have the same background? Some have gray, some have sand(?) and another, wood. I feel like the wood or gray are the easiest to understand when evaluating the images, although the wood is more instructive since it's a bit hard to judge the shadows against the gray, at least for me.

**Comment by hybridherbst** [comment]
Ideally they would have similar backgrounds, but it means I need to learn how to adjust those across systems.

- The sand one is the default env from usdview - I must admit I don't know how to change the environment/background in usdview 👀 – if you happen to know how I'm all ears!

- The wood one is actually my table, it's a picture from Augmented Reality on iOS 😄 I can try to find a roughly matching grey area to take another picture.

**Comment by jcowles** [comment]
Do you plan to make those additional changes or leave this in it's current state?

If you'd like to merge this as-is, can you switch it over to a non-draft PR?

**Comment by hybridherbst** [comment]
I'm still concerned by this:
>  I haven't been able to understand how it should correctly look with UsdPreviewSurface

but happy to make the other changes and switch to non-draft :)

**Comment by hybridherbst** [comment]
Simply forgot to switch to non-Draft... sorry about that! I think the screenshots can stay as-is until there's further clarification for how transparency/opacity is supposed to look like.

**Review by meshula — APPROVED** [review]

**Pull request merged**
