### PR TITLE
McUsd asset fixes

### PR DESCRIPTION
**Pull request by pablode**
This PR addresses a few issues with the McUsd asset I've encountered along the way.

1. 'inputs' prefixes to the DistantLight and DomeLight prim params were missing, causing the lights to not be used. This has already been noted before and was/is a limitation of the exporter: https://github.com/PixarAnimationStudios/USD/issues/2034
2023-05-24 18_39_53-E__usd-wg-assets_full_assets_McUsd_McUsd usda

2. Adding those prefixes makes apparent that the dome light is incorrectly rotated, and removing the Xforms fixes the issue.
2023-05-24 18_15_12-E__usd-wg-assets_full_assets_McUsd_McUsd usda 2023-05-24 18_15_56-E__usd-wg-assets_full_assets_McUsd_McUsd usda

3. The asset renders as white due to a very high dome light intensity value of 1560. Dividing the values by 1000 yields reasonable results. The asset looks fine in RPR, 3Delight, QuickLook and Storm:
2023-05-24 18_24_05-E__usd-wg-assets_full_assets_McUsd_McUsd usda 2023-05-24 18_24_20-E__usd-wg-assets_full_assets_McUsd_McUsd usda
Apparently the intensity values are not physically motivated, and it would be nice have additional tests with other renderers (Arnold, RenderMan, Karma): https://github.com/erich666/McUsd#physical-units-for-lights

Lastly, I've fixed a typo  in the `metersPerUnit` metadatum of the non-10cm asset, and applied the MaterialBindingAPI schema whenever needed (by using the usdfixbrokenpixarschemas tool). This should probably be done for many other assets in this repo.

PS: I don't think the dome light looks good with the low res and linear filtering. I've found [this possible replacement](https://www.realtimerendering.com/erich/minecraft/public/chunky/skymaps/MinecraftSkyDay.png) on Eric's site. After a slight modification it works, but I don't know about the licensing.

2023-05-24 19_32_56-E__usd-wg-assets_full_assets_McUsd_McUsd usda

cc @erich666

### CODE REVIEW

**Comment by erich666** [comment]
Thanks so much! Someone just pointed this PR to me - GIthub unfortunately didn't notify me about it, ugh. I'll try to figure out why that is (I've tried before, and failed). In the meantime, I'm at erich@acm.org if you answer and want me to know.

I have a better exporter (shares vertices, properly notes faces are not subdivision surfaces) at this point, but you've pointed out a bunch of things for me to look through and address. I suspect I won't touch the metersPerUnit value to 1m, for example, because this sometimes wreaks havoc with some viewers (two that come to mind are that default camera clip values don't get scaled, and there can be units confusion with emissive surfaces - [a weak area of UsdPreviewSurface](https://github.com/usd-wg/assets/tree/main/full_assets/McUsd#technical-details) anyway).

I hope to start working on this PR next week. Thanks again, and sorry it's fallen through the cracks.

**Comment by erich666** [comment]
Just to let you know, I'm still planning on getting to this task, but pre-SIGGRAPH doings and PaidWork(tm) absorbed my energy these past three weeks. August 14th I'm back on it.

**Comment by pablode** [comment]
No worries - thanks for the heads-up!

**Comment by erich666** [comment]
Wait, what? This issue is closed now? I started fixing things today, and plan on continuing.

Yes, "input:" was missing from a bunch of parameters, and I've fixed that today. Interestingly, some parsers (e.g., Omniverse's USD Composer) don't care, either form is fine, but, best to be compliant.

> Adding those prefixes makes apparent that the dome light is incorrectly rotated, and removing the Xforms fixes the issue.

Is there any test asset somewhere that shows the proper orientation? I made the DomeLight in USD Composer, where it looks fine. This means Composer likely has a bug, which I'd like to report. I don't see any asset in https://github.com/usd-wg/assets with "dome" in it (I'll save you the search). If there's a "here's a dome light, here's what it should look like" example anywhere, that would be useful for me making a fix. I appreciate that link to https://github.com/PixarAnimationStudios/OpenUSD/issues/2034, but no pic there. Or, documentation about DomeLight orientation might be sufficient to get it right on my end and then report a bug to NVIDIA.

> The asset renders as white due to a very high dome light intensity value of 1560. Dividing the values by 1000 yields reasonable results.

I should revisit this question and do a survey. Part of the problem is weak PBR light support in USD currently, leading to "1-100 is a good range" for various semi-unitless values. One major reason I made this USD test scene was, [as you surmised](https://github.com/erich666/McUsd#physical-units-for-lights), to point out the problems with the current specification. The scene looks good in USD Composer with these lights. I can tell NVIDIA that their lighting settings are wrong, but without an approved test scene that is considered correct (lights given in lux units), they're unlikely to change their system based on "others are picking lower values."

Is there any definitive source for how DistantLights and DomeLights are specified in physical terms?

**Comment by erich666** [comment]
Actually, you're right to close it, but I appreciate it being open until I come up with a separate fix.

Wow, how did I never notice those test files?! Too well-kept a secret. I may need to make a public "here are USD test resources" page... But, first, I'll give these a test - thanks. I've already logged a bug against Omniverse USD Composer and I see at least one other flakey importer at this point.

I've consulted with Anders and he was recommending setting the camera fStop to -10 or similar. For systems that respect that setting this might work. But I agree that it would be nicer to set "normal" settings for lights. The long-term solution is to have a solid, meaningful PBR light specification. I'm kind of tempted to just leave the "bad" (well, really, there's no correct answer, just guesses by each renderer) lights as-is, as a reminder that this area of the spec needs attention.

**Comment by erich666** [comment]
I've addressed these issues in [this new PR](https://github.com/usd-wg/assets/pull/52), so I think this PR can be closed. Thanks for reopening it as a reminder.

This PR brings up a few issues. Here's how my new PR addresses them. I definitely want review on it for opinions.

#1 and #3 - the input intensity should have indeed been labeled "inputs:intensity" instead of just "intensity". I at first tried to simply correct the variable names to "inputs:intensity". However, there's no agreement as to what "intensity" means among viewers. Anders Langlands has [a page showing the problem](https://github.com/anderslanglands/light_comparison) (which I've added to the README.md's here). He suggested playing tricks with "exposure", setting it to -10, so that over-bright lights would be dimmed down in Arnold, etc.

I decided to take a different solution: do not set any inputs:intensity at all. The behavior in viewers I've tested give these lights a default intensity value that they like. Well, some do - others might set these too bright or dim, but I have no control over that. Setting specific values is worse. In the McUsd* USDA files I note, for example:

    # The meaning of "intensity" varies among applications; no intensity often helps the viewer pick a default it likes.
    # This value is reasonable for USD Composer, for example, but not for other viewers:
    # float inputs:intensity = 1560

#2 - dome light orientation. The original McUsd indeed had a bug, having an incorrect orientation (rotated -90 around the X axis). I have removed this (and logged a bug against NVIDIA's USD Composer).

> the MaterialBindingAPI schema

I _think_ I've now added this properly (following what USD Composer is doing), please take a look. If it's not right, let me know what it should look like.

> I've fixed a typo in the metersPerUnit metadatum of the non-10cm asset

I do not change this default on purpose. I could probably just leave off this metadatum, but I think it's worth showing that both files are set to the default 0.01 (one centimeter) value. Inside the McUsd.usda file I instead scale the whole model up to meter scale by scaling by 100 (and in 10cm I scale by 10). I found this safer than actually changing that metadatum, which seems to have side effects on different systems, such as causing near-clipping problems with default cameras. The file's not really about testing this metadatum, though people are certainly welcome to change it themselves.

The new mesh representations now share vertex and normal data as possible, which is better than the old version. They also show the use of:

    uniform token subdivisionScheme = "none"

to avoid these being treated as subdivs.

That's it. I'm not a USD expert by any means. I'm pretty much following people's advice on what should be put in these files. For example, I've added extents in this new version, which I assume are in local coordinates for the meshes.

**Comment by meshula** [comment]
Great investigation as always :)
>I've added extents in this new version, which I assume are in local coordinates for the meshes.
Yes

**Comment by pablode** [comment]
> I decided to take a different solution: do not set any inputs:intensity at all.

Great idea with the default intensity! I have yet to test it.

> the MaterialBindingAPI schema

As the validation pipeline passes, this seems to be correct.

> I do not change this default on purpose.

Ah, sorry, I think I misunderstood the idea of this variant in the first place. I understand that this change causes problems, as the camera-related fields `horizontalAperture`, `horizontalApertureOffset`, `verticalAperture`, `verticalApertureOffset` and `focalLength` are expressed in tenths of the world unit, and should have been adjusted accordingly.

Also the mesh data, extents and subdivisionScheme changes seems reasonable. Regarding USDZ: I used usdzip in the same way.

> I'm not a USD expert by any means.

Me neither. But we're getting there :D

**Comment by erich666** [comment]
Thanks for looking this over - it helps me feel a bit more confident that these are reasonable fixes. The light intensity trick at least more or less works for UsdView (the environment light is overdone), but is definitely a YMMV. What's funny is that my original wrong way of setting intensity worked for two apps: USD Composer (where it accepts the intensity in this form) and UsdView (where it doesn't and sets a default). Fixing the intensity input "broke" how it looks on UsdView! Ah well. Part of the point of this test model is that lights and emissive surfaces need more careful definition.

**Pull request closed without merging**
