### PR TITLE
Convert glTF2.0 animations to usdz examples

### PR DESCRIPTION
**Pull request by beersandrew**
- Added docs to documentation/README.md to describe the process for conversion
- Let me know if the locations here are not best, happy to move them to another directory
- Let me know if some of the example gifs should be re-done

### CODE REVIEW

**Comment by crydalch** [comment]
Thank you for adding the PR! A thought that just occurred to me: should we make a USDZ sub-dir inside of `test_assets` and put all of these in there?

USDZ is important and has enough of its own quirks/requirements, that I think it's worth considering. That would help people looking for USDZ-specific examples, to not have to scan every folder to see which ones may or may not contain a USDZ file...

**Comment by beersandrew** [comment]
> Thank you for adding the PR! A thought that just occurred to me: should we make a USDZ sub-dir inside of `test_assets` and put all of these in there?
> 
> USDZ is important and has enough of its own quirks/requirements, that I think it's worth considering. That would help people looking for USDZ-specific examples, to not have to scan every folder to see which ones may or may not contain a USDZ file...

Thanks for the suggestion, I've added a commit to do that. I know one of the driving forces for doing these conversions was to create more animated samples as well, which most of these are. Being new to the space I can't help but notice a lot of different segmentations and I'm not sure if there's a great way to organize it all so that it's intuitive for people. 

Will someone appreciate a segmentation of static assets vs animated assets? maybe `test_assets/animated/usdz-only`

Is having only a usdz representation of an asset limiting and would it be best to add in usda, usdc or some other extensions in these folders as well?

**Comment by pjcozzi** [comment]
@beersandrew it is very cool to see the usdz examples from these glTF models.  This is going to be so helpful for glTF and USD interop.

@emackey is there someone from the glTF community familiar with these sample models and animations who could give quick feedback?  Feels right up your alley if you had a few cycles.

**Comment by meshula** [comment]
I'm going to defer updates as necessary to subsequent issues & PRs. Thanks for doing this @beersandrew !

**Pull request merged**
