### PR TITLE
Add the Open Chess Set

### PR DESCRIPTION
**Pull request by pablode**
This PR contributes a USD+MaterialX version of the Open Chess Set.

Please see the [README](https://github.com/pablode/usd-wg-assets/tree/open-chess-set/full_assets/OpenChessSet) for a description and teaser image.

### CODE REVIEW

**Comment by crydalch** [comment]
This is great @pablode! Here are thoughts we had:

- `/Geom` should be an Xform, not a Scope, so the whole set can transform the whole chess set at once
- Probably better to rename `/Geom` to `/OpenChessSet` or `/chess_set`?
- The materials should be referenced underneath the chess set prim, so the mtlx can be seen/edited if the asset is referenced (i.e. `/chess_set/materials`)
- The black and white pieces should probably get their own intermediate transforms beneath the asset's top-level prim- Each piece geometry should payloaded instead of referenced, and have extent information lofted to the payloading prim
- Kind should be specified everywhere (_component_ for board and pieces, `/Geom` should be an _assembly_, and any xforms/scopes between a component pieces and the top prim _group_)
- It'd be really nice if the chess pieces inherited from generic class prims (i.e. "pawn", "knight", etc...) and the entire chess set should also probably inherit from a "chess set"

Does that make sense? A lot of these suggestions are informed by the [Asset Structure Guidelines](https://github.com/usd-wg/assets/blob/main/docs/asset-structure-guidelines.md#overview) doc.

Thanks!

**Comment by pablode** [comment]
@crydalch thank you again for these insightful comments! I've addressed some of them in the recent push. I'll implement payloading and inherits arcs in the next days.

PS: I see that previous PRs have been merged with their history intact. I think it might be worthwhile to 'squash'-merge in order to keep the repo size small?

**Comment by meshula** [comment]
Good note on Squash and merge!

**Comment by meshula** [comment]
@pablode This is looking good, thanks for the work :) Please drop a note here when you think it's ready to check in ~ it's fine for iteration to take the form of subsequent PRs.

**Comment by pablode** [comment]
@crydalch @meshula  I've reworked the asset to comply with the guidelines - please have another look 🙂

Some questions from my side:
	- is the class inheritance properly implemented?
	- what do you think of the payloaded per-component materials and textures?
	- it would make sense to have a global Black/White variant - should this be implemented using class inheritance?

**Comment by crydalch** [comment]
Sorry for the delayed follow-up @pablode, this is looking great! Here are just a few more thoughts:

- The class/inherits looks good!
- The assetinfo doesn't need to live in the payload, it can live in the `<asset>.usd` layer
- Having the material bindings/variants in the payload works; though I think it's probably cleaner to have those in a dedicated materials layer.
- I think we want to convert the usd files to ascii? Or at least make have the `<asset>.usd` and `<asset>_payload.usd` layers be ascii
- Instead of untyped prims within the asset, `<asset>/Materials` should be a Scope, and have the mtlx reference live there; so the reference on the `Materials` scope would be `prepend references = @./Rook_mat.mtlx@</MaterialX/Materials>`. The rest of the Shaders/NodeGraphs prims from the .mtlx document aren't directly useable, afaik.
- To allow for a future improvement of having both proxy and render purpose geometry in each asset, `/Geom` in each of the assets should be a Scope, and we can put the Mesh prim(s) inside of that. We could go further and setup a low-res proxy, which would go in `<asset>/Geom/Proxy` and then put the existing mesh under `<asset>/Geom/Render`, but maybe that's something we can discuss in the next wg meeting, or on slack?

I've attached an example of the Rook to illustrate some of the comments. Thanks @pablode !

rook_adjusted_hierarchy

[Rook.zip](https://github.com/usd-wg/assets/files/10138124/Rook.zip)

**Review by Lucas3Dspain — COMMENTED** [review]
I was testing the rock.usd file on Solaris karma and in Maya (as usdProxyShape) and I have the normals inverted because of the negative scale. 
Where did you get the inverted normals? usdView? I would suggest leaving the scale at 1

**Comment by pablode** [comment]
@crydalch Thanks again for the feedback, and sorry for the delay! The example files were helpful, and additionally to the points, I've addressed the extent hints lofting mentioned above. I've left the geometry USD files in binary form to reduce the size of the asset inside the repo, and would prefer to defer the proxy geometry to a separate/subsequent contribution.

@Lucas3Dspain Thank you for testing! Yes, I've used Storm (and RPR), but I believe I was mislead with the normal map behaviour due to two open colorspace related issues: [#1523](https://github.com/PixarAnimationStudios/USD/issues/1523) [#1878](https://github.com/PixarAnimationStudios/USD/issues/1878). As far as I know, the behaviour in Karma is more robust/correct, as only `<image>`s of type _color3_ are sRGB-decoded, and `<image>`s of type _vector3_ (which are used for the normal maps) are not. Hence, I've reverted the change.

@meshula @crydalch How do we proceed? One last review to confirm it's in a mergeable state?

**Comment by crydalch** [comment]
> I've left the geometry USD files in binary form to reduce the size of the asset inside the repo, and would prefer to defer the proxy geometry to a separate/subsequent contribution.

@pablode I think that's fine. We can look into adding purpose to this later if it's desired. Thanks!

My 2c: I think if there aren't any other outstanding issues after our next WG meeting this Friday, we can go ahead and merge. But we can all chat then and figure out when we can merge the chess set.

This is all looking great, thank you!

**Comment by meshula** [comment]
Were there outstanding issues discussed on Friday?

My vote is to land it with alacrity.

**Comment by jcowles** [comment]
There were no additional changes!

**Pull request merged**
