### PR TITLE
usdchecker: print file name and don't early-abort

### PR DESCRIPTION
**Pull request by pablode**
Some workflow tweaks. See it in action here: https://github.com/pablode/usd-wg-assets/pull/8

### CODE REVIEW

**Comment by meshula** [comment]
at pablode#8 it says the wokflow needs approval? Or am I not looking in the right place to see it in action?

**Comment by pablode** [comment]
Ah, interesting. This is because the remote branch has been pushed to, and RY is a first-time contributor. I've run the workflow again.

**Comment by pablode** [comment]
And apparently there is also a flaw with the detection of PR file changes (it only considers the recent push). I'll take a look at it.

**Comment by jcowles** [comment]
Other issues aside, thanks for addressing the readability of the output!

**Comment by jcowles** [comment]
btw, @pablode looking at the output in your example, GitHub says the usdchecker passed, but usdchecker had many failures - is it possible that it's just reporting the final exit code from the loop (which was successful) to GitHub?

**Comment by pablode** [comment]
Yes, I think pipefail was the wrong option. Should use a trap instead.

**Comment by pablode** [comment]
@jcowles I've reworked the error handling, and it works now. While we're at it, perhaps we can relax the **Fork pull request workflows from outside collaborators** condition to "first-time contributors new to GitHub"?

**Comment by meshula** [comment]
@pablode @jcowles I relaxed the workflow approval. If we get hit by spammers we can bump it up again.

**Comment by jcowles** [comment]
nice and nice!
merging!

**Pull request merged**
