### PR TITLE
feat: add initial card images

### PR DESCRIPTION
**Pull request by beersandrew**
Ran cards generation script with --image-width 512, this locks the width to 512, however for some more elongated shapes it still produces large images, not sure if there's a better strategy there, I suppose there could be some math the make the longest side fit to the input width.

Many test assets had empty card images so i didn't commit them

### CODE REVIEW

**Comment by beersandrew** [comment]
> I notice ElephantWithMonochord is empty ~ I wonder why?

This bounding box for the elephant has always been off. I think I have a version that is fixed, but I have to double check, maybe that's a separate PR?

> I do think it would be good to go with maximum dimension instead of strictly width.

Okay, I'll update the script for this

**Comment by meshula** [comment]
If you have a fix for the elephant's bounds that would be a great separate PR :)

**Comment by beersandrew** [comment]
> If you have a fix for the elephant's bounds that would be a great separate PR :)

Improved elephant PR: https://github.com/usd-wg/assets/pull/76

**Comment by beersandrew** [comment]
> I do think it would be good to go with maximum dimension instead of strictly width.

committed a fix for this, let me know what you think.

**Review by meshula — APPROVED** [review]
Thanks for updating the enormous images to be 512 tall :) looking good

**Pull request merged**
