### PR TITLE
Run usdchecker for full_assets

### PR DESCRIPTION
**Pull request by beersandrew**
These changes make usdchecker pass for all full_assets. Some assumptions were made, mainly:

- whenever metersPerUnit was not listed, 0.01 was added
- When shaders are nested inside other shaders, they can be brought to the same level as long as the reference paths are updated
- scale recommendations from usdchecker are valid
- bias recommendations from usdchecker are valid
- updates from usdfixbrokenpixarchemas do the right thing
- When gprims are nested, it's valid to pull out the child and put it at the same level in the hierarchy

### CODE REVIEW

**Comment by meshula** [comment]
This is great!

@hybridherbst Could you give this a once over? I'm wondering if there's a pattern in an export pipeline we are using that needs to be addressed in order to generate assets that don't cause check warnings? Perhaps a script needs updating.

**Comment by hybridherbst** [comment]
@meshula in my experience creating files for QuickLook I find it pretty rare to produce files that work in QuickLook _and_ pass usdchecker, as QuickLook features and what the usdchecker checks are not in sync for years (at least not with the `--arkit` flag, the more general checks may be fine!). 

That being said, above changes to the Bike and Elephant look good, it's only `MaterialBindingAPI` and `SkelBindingAPI` additions as far as I can see (please correct me if wrong). I'm not certain that Unity's USD package generates these properly by now on export; I'll ask Michael :)

**Comment by meshula** [comment]
Thanks for the notes, much appreciated!

**Comment by jcowles** [comment]
Thanks Andy!!

**Pull request merged**
